name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Publish Site
        uses: poolpOrg/hugo-gh-pages@master
        env:
          INPUT_HUGOVERSION: 0.144.2
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
